import {SALE_STATUSES,validateClient} from './engine.js';

export function createClientsUI(api){
  const {esc,money,uid,toast}=api;
  const dialog=document.querySelector('#client-editor');
  let query='',edit=null,busy=false;
  const state=()=>api.getState(),clients=()=>state().clients??[],sales=()=>state().sales??[],clone=x=>structuredClone(x);
  const norm=v=>String(v??'').trim().toLocaleLowerCase('pl');
  const clientSales=id=>sales().filter(s=>s.clientId===id).sort((a,b)=>(b.dueDate+'T'+(b.dueTime||'')).localeCompare(a.dueDate+'T'+(a.dueTime||'')));
  const activeSale=s=>!['delivered','cancelled'].includes(s.status);
  function fresh(){const now=new Date().toISOString();return {id:uid(),name:'',phone:'',email:'',address:'',preferences:'',notes:'',createdAt:now,updatedAt:now};}
  function filtered(){const q=norm(query);return clients().filter(c=>!q||[c.name,c.phone,c.email,c.address,c.preferences,c.notes].some(v=>norm(v).includes(q))).sort((a,b)=>a.name.localeCompare(b.name,'pl',{sensitivity:'base'}));}
  function summary(c){const orders=clientSales(c.id),done=orders.filter(s=>s.status==='delivered'),active=orders.filter(activeSale),value=done.reduce((sum,s)=>sum+s.price,0);return {orders,done,active,value};}
  function render(){
    const list=filtered();
    const linked=new Set(sales().map(s=>s.clientId).filter(Boolean));
    const repeat=clients().filter(c=>clientSales(c.id).length>=2).length;
    const activeClients=clients().filter(c=>clientSales(c.id).some(activeSale)).length;
    return `<div class="heading"><div><h1>Klienci</h1><p>Kartoteka klientów połączona z historią zamówień — bez Excela.</p></div><div class="actions"><button class="primary" data-action="clients-new">+ Dodaj klienta</button></div></div>
    <div class="metrics"><div class="metric featured"><span class="label">Klienci w bazie</span><strong>${clients().length}</strong><span class="muted">Zapisani w IndexedDB na tym urządzeniu</span></div><div class="metric"><span class="label">Z historią zamówień</span><strong>${linked.size}</strong><span class="muted">Powiązani przynajmniej z jednym zamówieniem</span></div><div class="metric"><span class="label">Klienci powracający</span><strong>${repeat}</strong><span class="muted">Co najmniej 2 powiązane zamówienia</span></div><div class="metric"><span class="label">Z aktywnym zamówieniem</span><strong>${activeClients}</strong><span class="muted">Zapytanie, produkcja lub odbiór w toku</span></div></div>
    <section class="card"><div class="body client-search"><label>Szukaj klienta<input id="clients-search" type="search" value="${esc(query)}" placeholder="Imię i nazwisko, telefon, e-mail, adres lub notatka"></label><p class="help">Lista jest przechowywana w tej samej lokalnej bazie IndexedDB co receptury i zamówienia. Pełna kopia JSON z sekcji „Dane i pomoc” zawiera również klientów.</p></div></section>
    <div class="client-list spaced">${list.map(c=>{const s=summary(c),last=s.orders[0];return `<article class="card client-card"><div class="client-avatar" aria-hidden="true">${esc(c.name.trim().slice(0,1).toLocaleUpperCase('pl')||'K')}</div><div class="client-main"><div class="client-title"><div><h2>${esc(c.name)}</h2><p>${esc(c.phone)||'Bez telefonu'}${c.email?' · '+esc(c.email):''}</p></div><span class="pill">${s.orders.length} ${s.orders.length===1?'zamówienie':'zamówień'}</span></div><p class="client-excerpt">${esc(c.preferences||c.notes||c.address||'Brak dodatkowych informacji.')}</p><div class="client-footer"><span>${last?`Ostatnie: <strong>${last.dueDate.split('-').reverse().join('.')}</strong> · ${esc(last.title)}`:'Brak historii zamówień'}</span><div class="actions"><button class="small" data-action="clients-detail" data-id="${esc(c.id)}">Karta klienta</button><button class="small primary" data-action="clients-edit" data-id="${esc(c.id)}">Edytuj</button></div></div></div></article>`;}).join('')||`<section class="card empty"><h2>${clients().length?'Brak klientów pasujących do wyszukiwania':'Dodaj pierwszego klienta'}</h2><p>${clients().length?'Wyczyść wyszukiwanie albo wpisz inną frazę.':'Kartoteka pozwoli wybierać klienta przy kolejnych zamówieniach i automatycznie budować historię.'}</p><button class="primary" data-action="clients-new">+ Dodaj klienta</button></section>`}</div>`;
  }
  const field=(label,key,value,type='text',attrs='')=>`<label>${label}<input name="${key}" type="${type}" value="${esc(value)}" ${attrs}></label>`;
  const area=(label,key,value,placeholder='')=>`<label class="wide">${label}<textarea name="${key}" maxlength="12000" placeholder="${esc(placeholder)}">${esc(value)}</textarea></label>`;
  function formHtml(c){return `<form id="client-form"><div class="cardheader"><div><span class="muted">Kartoteka klientów</span><h2>${clients().some(x=>x.id===c.id)?'Edytuj klienta':'Nowy klient'}</h2></div><button class="icon" type="button" data-client="close" aria-label="Zamknij">×</button></div><div class="body"><div id="client-error" role="alert"></div><div class="fields two">${field('Imię i nazwisko / nazwa klienta','name',c.name,'text','required maxlength="160"')}${field('Telefon','phone',c.phone,'tel','maxlength="300"')}${field('E-mail','email',c.email,'email','maxlength="300"')}<label class="wide">Adres / domyślne miejsce dostawy<input name="address" maxlength="1000" value="${esc(c.address)}" placeholder="Opcjonalnie"></label>${area('Preferencje i ustalenia','preferences',c.preferences,'Np. ulubione smaki, styl dekoracji, preferowany sposób kontaktu')}${area('Notatki wewnętrzne','notes',c.notes,'Informacje organizacyjne przydatne przy kolejnych zamówieniach')}</div><p class="help">Dane pozostają w przeglądarce na tym urządzeniu. Zapisuj tylko informacje potrzebne do obsługi zamówień.</p></div><footer><button type="button" data-client="close">Anuluj</button><button type="submit" class="primary" id="client-save">Zapisz klienta</button></footer></form>`;}
  function open(id){edit=id?clone(clients().find(c=>c.id===id)):fresh();if(!edit)return;dialog.innerHTML=formHtml(edit);if(!dialog.open)dialog.showModal();}
  function detail(id){const c=clients().find(c=>c.id===id);if(!c)return;edit=clone(c);const s=summary(c);dialog.innerHTML=`<div class="cardheader"><div><span class="muted">Karta klienta</span><h2>${esc(c.name)}</h2></div><button class="icon" data-client="close" aria-label="Zamknij">×</button></div><div class="body"><div class="client-detail-grid"><div><h3>Kontakt</h3><p>${esc(c.phone)||'Brak telefonu'}${c.email?'<br>'+esc(c.email):''}${c.address?'<br>'+esc(c.address):''}</p></div><div><h3>Historia</h3><p>${s.orders.length} zamówień · ${s.done.length} wydanych<br>Wartość wydanych: <strong>${money(s.value)}</strong><br>Aktywne: ${s.active.length}</p></div></div><h3 class="spaced">Preferencje i ustalenia</h3><p class="prewrap">${esc(c.preferences)||'Brak.'}</p><h3>Notatki wewnętrzne</h3><p class="prewrap">${esc(c.notes)||'Brak.'}</p><h3 class="spaced">Historia zamówień</h3>${s.orders.length?`<div class="client-order-list">${s.orders.map(o=>`<button type="button" data-client="order" data-order="${esc(o.id)}"><span><strong>${esc(o.title)}</strong><small>${esc(o.number)} · ${o.dueDate.split('-').reverse().join('.')} · ${SALE_STATUSES[o.status]}</small></span><strong>${money(o.price)}</strong></button>`).join('')}</div>`:'<p class="help">Ten klient nie ma jeszcze powiązanych zamówień. Przy tworzeniu zamówienia wybierz go z pola „Klient z bazy”.</p>'}<p class="help">Dodano ${new Date(c.createdAt).toLocaleString('pl-PL')} · zmieniono ${new Date(c.updatedAt).toLocaleString('pl-PL')}</p></div><footer><button data-client="delete" class="danger">Usuń klienta</button><button class="primary" data-client="edit">Edytuj</button></footer>`;if(!dialog.open)dialog.showModal();}
  function readForm(){const f=dialog.querySelector('#client-form');if(!f||!edit)return;for(const k of ['name','phone','email','address','preferences','notes'])edit[k]=f.elements[k].value;}
  function showError(message){const el=dialog.querySelector('#client-error');if(el)el.innerHTML=`<div class="error">${esc(message)}</div>`;else toast(message);}
  function setBusy(v){busy=v;dialog.querySelectorAll('button,input,textarea').forEach(x=>x.disabled=v);const b=dialog.querySelector('#client-save');if(b)b.textContent=v?'Zapisywanie…':'Zapisz klienta';}
  async function save(){if(busy||!edit)return;readForm();try{const item=clone(edit);for(const k of ['name','phone','email','address','preferences','notes'])item[k]=item[k].trim();item.updatedAt=new Date().toISOString();validateClient(item);const next=clone(state());next.clients=next.clients??[];const at=next.clients.findIndex(c=>c.id===item.id);if(at<0)next.clients.push(item);else next.clients[at]=item;setBusy(true);await api.commit(next);dialog.close();edit=null;toast('Zapisano klienta.');}catch(e){showError(e.message);}finally{setBusy(false);}}
  async function remove(){if(!edit)return;const linked=clientSales(edit.id);const text=linked.length?`Klient ma ${linked.length} powiązanych zamówień. Zamówienia zostaną zachowane z zapisanymi danymi klienta, ale odłączone od kartoteki.`:'Usunięcie klienta można cofnąć tylko z wcześniejszej kopii JSON.';if(!window.confirm('Usunąć klienta „'+edit.name+'”?\n\n'+text))return;const next=clone(state());next.clients=next.clients.filter(c=>c.id!==edit.id);for(const sale of next.sales??[])if(sale.clientId===edit.id)sale.clientId=null;setBusy(true);try{await api.commit(next);dialog.close();edit=null;toast('Usunięto klienta. Zamówienia pozostały w bazie.');}finally{setBusy(false);}}
  async function handle(b){const {action,id}=b.dataset;switch(action){case 'clients-new':open();break;case 'clients-edit':open(id);break;case 'clients-detail':detail(id);break;}}
  function close(){dialog.close();edit=null;}
  dialog.addEventListener('submit',e=>{e.preventDefault();save();});
  dialog.addEventListener('cancel',e=>{e.preventDefault();if(!busy)close();});
  dialog.addEventListener('click',async e=>{const b=e.target.closest('[data-client]');if(!b||busy)return;try{if(b.dataset.client==='close'){close();return;}if(b.dataset.client==='edit'){open(edit.id);return;}if(b.dataset.client==='delete'){await remove();return;}if(b.dataset.client==='order'){dialog.close();edit=null;api.openSale(b.dataset.order);return;}}catch(err){showError(err.message);}});
  document.querySelector('#app').addEventListener('input',e=>{if(e.target.id!=='clients-search')return;query=e.target.value;const pos=e.target.selectionStart;api.render();const input=document.querySelector('#clients-search');if(input){input.focus();input.setSelectionRange(pos,pos);}});
  return {render,handle,open,detail,fresh};
}
