// Original demonstration instructions; quantities come from the calculation engine.
// Technique references are listed in README, not a tested production formulation.
export function demoSteps(id){
  const step=(title,groups,text,minutes=null,temperature=null)=>({title,groups,text,minutes,temperature});
  const chocolate=id==='chocolate-cake';
  if(!chocolate&&id!=='raspberry-cake')return [];
  const steps=[step('Zaplanuj pracę i przygotuj formę',[], 'To przykładowa procedura dla demonstracyjnej receptury. Zacznij dzień przed dekorowaniem. Przygotuj formę {forma}, papier do pieczenia, wagę, mikser, szpatułkę i rant do składania. Wysokość {wysokosc} cm oznacza gotowy tort. Nie wlewaj całej masy do zbyt niskiej formy: podziel ją na wypieki. Dno wyłóż papierem. Ilości przy krokach obejmują {liczba_tortow} tortów. Jaja do biszkoptu doprowadź do temperatury pokojowej, nabiał do kremu pozostaw w lodówce.')];
  if(chocolate)steps.push(step('Przygotuj bazę kremu czekoladowego',['Krem'],'Użyj tylko śmietanki i czekolady z sekcji Krem. Czekoladę posiekaj, śmietankę podgrzej do wyraźnego parowania. Zalej nią czekoladę, odczekaj chwilę i wymieszaj do gładkiej masy. Mascarpone zostaw na później. Po przestudzeniu przykryj i wstaw bazę do lodówki na noc. Przed ubijaniem musi być zimna w całej objętości.',720,4));
  steps.push(step('Ubij jaja z cukrem',['Biszkopt'],'Oddziel białka od żółtek. Białka ubij do piany, następnie dosypuj cukier z sekcji Biszkopt małymi porcjami, stale miksując. Gdy piana jest gęsta i błyszcząca, dodawaj kolejno żółtka. Nie dodawaj tu cukru przeznaczonego do kremu.'),
  step('Dodaj suche składniki',['Biszkopt'],chocolate?'Przesiej razem mąkę i kakao z sekcji Biszkopt. Dodaj do masy jajecznej w kilku porcjach. Mieszaj szpatułką od dna ku górze tylko do zniknięcia suchej mąki. Przełóż do przygotowanej formy.':'Przesiej mąkę z sekcji Biszkopt. Dodaj do masy jajecznej w kilku porcjach razem z wanilią. Delikatnie połącz szpatułką od dna ku górze. Przełóż do przygotowanej formy.'),
  step('Upiecz biszkopt',[],'Wstaw do wcześniej rozgrzanego piekarnika, tryb góra–dół. Dla formy bazowej zacznij kontrolę około 35. minuty; orientacyjnie pieczenie zajmuje 35–45 minut. Patyczek wbity w środek powinien wyjść bez surowego ciasta. Dla innego rozmiaru lub podziału na wypieki kontroluj każdy wypiek oddzielnie. Czasu nie mnożymy przez przelicznik składników.',35,170),
  step('Wystudź i podziel na blaty',[],'Pozostaw biszkopt do całkowitego ostygnięcia. Oddziel boki od formy cienkim nożem. Wyrównaj wierzch i przekrój na {blaty} blatów, aby uzyskać {przelozenia} przełożeń kremem. Nie nakładaj kremu na ciepłe ciasto.'));
  if(chocolate)steps.push(step('Ubij krem czekoladowy',['Krem'],'Zimną bazę śmietankowo-czekoladową połącz z zimnym mascarpone z sekcji Krem. Miksuj na umiarkowanych obrotach tylko do otrzymania stabilnego kremu. Przerwij, gdy masa utrzymuje kształt; zbyt długie ubijanie może ją zwarzyć. To etap wykorzystania wcześniej przygotowanej bazy, nie kolejna porcja śmietanki i czekolady.'));
  else steps.push(step('Przygotuj maliny',['Owoce'],'Świeże maliny delikatnie opłucz, odsącz i dokładnie osusz. Mrożonych nie układaj zamrożonych między blatami: przygotuj je według instrukcji na opakowaniu i usuń nadmiar soku, a przed składaniem ostudź. W tej wersji maliny są osobną warstwą owoców; nie dodajemy żelatyny ani dodatkowego cukru.'),step('Ubij krem waniliowy',['Krem'],'Cukier z sekcji Krem zmiel na puder. Do zimnej misy przełóż schłodzone mascarpone i śmietankę, dodaj przygotowany puder. Miksuj, obserwując gęstość; zakończ, gdy krem jest jednolity i trzyma kształt. Nie miksuj dalej, aby nie powstały grudki. Użyj całej ilości tej sekcji jako puli do podziału między przełożenia.'));
  steps.push(step('Przełóż tort w rancie',chocolate?['Krem']:['Krem','Owoce'],chocolate?'Umieść pierwszy blat na podkładzie w rancie. Podziel gotowy krem na {przelozenia} porcji. Rozsmaruj porcję kremu na każdym przełożeniu, zamykając tort kolejnymi blatami. Ostatni blat ułóż płasko i delikatnie dociśnij. Nie odmierzaj ponownie składników z tabeli — używasz już przygotowanego kremu.':'Umieść pierwszy blat na podkładzie w rancie. Podziel gotowy krem i przygotowane maliny na {przelozenia} porcji. Na każdym przełożeniu rozprowadź porcję kremu i rozłóż maliny, pozostawiając brzeg z samego kremu. Przykrywaj kolejnymi blatami. Nie dodawaj ponownie składników z tabeli.'),
  step('Schłodź złożony tort',[],'Pozostaw tort w rancie w lodówce, aby masa się ustabilizowała. Zaplanowane minimum to 6 godzin; wygodnie zostawić tort na noc. Przed zdjęciem rantu sprawdź, czy boki i krem są stabilne. Podany czas jest etapem chłodzenia, nie aktywnej pracy.',360,4),
  step('Przygotuj tynk',['Tynk'],'Użyj masła i czekolady z sekcji Tynk. Masło powinno być miękkie, lecz nie płynne. Czekoladę rozpuść delikatnie w kąpieli wodnej, nie dopuszczając do kontaktu z wodą. Ostudź do temperatury zbliżonej do masła, zachowując płynność. Masło ubij na jasną masę, stopniowo dodaj czekoladę i wymieszaj do gładkości.'),
  step('Otynkuj i udekoruj',['Tynk'],'Zdejmij rant z dobrze schłodzonego tortu. Najpierw rozprowadź cienką warstwę tynku, która zbierze okruchy, i schłodź do jej stężenia. Następnie nałóż resztę tynku na boki i wierzch, wygładź skrobką. Dodaj dekoracje zgodne z zamówieniem. Przed transportem ponownie schłodź; sprawdź napis, podkład i opakowanie. Przy torcie piętrowym zastosuj odpowiednie podkłady i wsporniki — sam tynk nie stanowi konstrukcji nośnej.'));
  return steps;
}
