/* Pracownia Tortów — pure calculation engine, all money in PLN. */
export const UNITS={g:{dimension:'mass',factor:1,base:'g'},kg:{dimension:'mass',factor:1000,base:'g'},ml:{dimension:'volume',factor:1,base:'ml'},l:{dimension:'volume',factor:1000,base:'ml'},szt:{dimension:'count',factor:1,base:'szt'}};
export const MODES={volume:'Objętość — biszkopt',filling:'Powierzchnia × przełożenia',coating:'Wierzch + boki — tynk',area:'Powierzchnia — pojedyncza warstwa',perimeter:'Obwód — dekoracja brzegu',fixed:'Stała ilość na piętro'};
function finite(n,label,min=0,max=1e9){if(typeof n!=='number'||!Number.isFinite(n)||n<min||n>max)throw Error(`${label}: podaj liczbę od ${min} do ${max}.`);return n;}
export function geometry(p){if(!p||!['round','rect'].includes(p.shape))throw Error('Nieznany kształt formy.');finite(p.height,'Wysokość',0.1,200);finite(p.layers,'Liczba przełożeń',1,30);if(!Number.isInteger(p.layers))throw Error('Liczba przełożeń musi być całkowita.');let area,perimeter;if(p.shape==='round'){finite(p.diameter,'Średnica',1,200);area=Math.PI*(p.diameter/2)**2;perimeter=Math.PI*p.diameter;}else{finite(p.width,'Szerokość',1,200);finite(p.length,'Długość',1,200);area=p.width*p.length;perimeter=2*(p.width+p.length);}return {area,perimeter,volume:area*p.height,coating:area+perimeter*p.height};}
export function scale(mode,base,target){const b=geometry(base),t=geometry(target);switch(mode){case 'volume':return t.volume/b.volume;case 'filling':return t.area/b.area*target.layers/base.layers;case 'coating':return t.coating/b.coating;case 'area':return t.area/b.area;case 'perimeter':return t.perimeter/b.perimeter;case 'fixed':return 1;default:throw Error('Nieznany sposób skalowania.');}}
export function convert(q,from,to){finite(q,'Ilość');if(!UNITS[from]||!UNITS[to]||UNITS[from].dimension!==UNITS[to].dimension)throw Error('Niezgodne jednostki. Nie przeliczamy gramów na mililitry bez gęstości.');return q*UNITS[from].factor/UNITS[to].factor;}
export function validateIngredient(i){if(!i||typeof i.id!=='string'||!i.id||typeof i.name!=='string'||!i.name.trim())throw Error('Składnik musi mieć nazwę i identyfikator.');if(!UNITS[i.unit])throw Error('Nieznana jednostka składnika.');finite(i.pack,'Wielkość opakowania',0.001);finite(i.price,'Cena opakowania');finite(i.loss,'Strata składnika',0,95);finite(i.stock,'Zapas');if(typeof i.allergens!=='string'||typeof i.supplier!=='string')throw Error('Nieprawidłowy opis składnika.');return i;}
export function validateRecipe(r,ingredients){if(!r||typeof r.id!=='string'||!r.id||typeof r.name!=='string'||!r.name.trim()||typeof r.notes!=='string')throw Error('Receptura musi mieć nazwę.');geometry(r.base);if(!Array.isArray(r.rows)||!r.rows.length||r.rows.length>300)throw Error('Receptura musi zawierać od 1 do 300 pozycji.');r.rows.forEach(x=>{const i=ingredients.find(i=>i.id===x.ingredientId);if(!i)throw Error('Receptura odwołuje się do nieistniejącego składnika.');finite(x.qty,'Ilość w recepturze',0.001);convert(x.qty,x.unit,UNITS[i.unit].base);if(!MODES[x.mode])throw Error('Nieprawidłowy sposób skalowania.');if(typeof x.group!=='string')throw Error('Nieprawidłowa sekcja receptury.');});return r;}
export function validateOrder(o,recipes){if(!o||typeof o.name!=='string')throw Error('Nieprawidłowe dane kalkulacji.');if(!Array.isArray(o.tiers)||o.tiers.length<1||o.tiers.length>20)throw Error('Wymagane 1–20 pięter.');o.tiers.forEach(t=>{if(!recipes.some(r=>r.id===t.recipeId))throw Error('Brakuje receptury piętra.');geometry(t);});for(const k of ['reserve','hours','rate','packaging','decoration','delivery','energyKwh','energyPrice','overhead','margin','roundTo','portionVolume'])finite(o[k],k);finite(o.reserve,'Zapas technologiczny',0,100);finite(o.margin,'Marża',0,95);finite(o.roundTo,'Zaokrąglenie',0.01,1000);finite(o.portionVolume,'Objętość porcji',10,2000);finite(o.count,'Liczba tortów',1,1000);if(!Number.isInteger(o.count))throw Error('Liczba tortów musi być całkowita.');if(o.sale!==null)finite(o.sale,'Cena sprzedaży');return o;}
export function calculate(ingredients,recipes,order){ingredients.forEach(validateIngredient);recipes.forEach(r=>validateRecipe(r,ingredients));validateOrder(order,recipes);const rows=[],used=new Map(),allergens=new Set();let volume=0;const tiers=order.tiers.map((t,index)=>{const recipe=recipes.find(r=>r.id===t.recipeId);volume+=geometry(t).volume;for(const x of recipe.rows){const i=ingredients.find(i=>i.id===x.ingredientId),unit=UNITS[i.unit].base,factor=scale(x.mode,recipe.base,t),net=convert(x.qty,x.unit,unit)*factor*(1+order.reserve/100)*order.count,gross=net/(1-i.loss/100),packBase=i.pack*UNITS[i.unit].factor,cost=gross/packBase*i.price;rows.push({...x,tier:index+1,name:i.name,unit,factor,net,gross,cost});let sum=used.get(i.id);if(!sum){sum={id:i.id,name:i.name,unit,net:0,gross:0,cost:0,packBase,packPrice:i.price,stock:i.stock*UNITS[i.unit].factor};used.set(i.id,sum);}sum.net+=net;sum.gross+=gross;sum.cost+=cost;if(i.allergens.trim())allergens.add(i.allergens.trim());}return {recipe:recipe.name,volumeFactor:scale('volume',recipe.base,t),portionEstimate:Math.max(1,Math.floor(geometry(t).volume/order.portionVolume))};});const shopping=[...used.values()].map(x=>{const missing=Math.max(0,x.gross-x.stock),packs=missing?Math.ceil(missing/x.packBase-1e-12):0;return {...x,missing,packs,buyCost:packs*x.packPrice,leftover:x.stock+packs*x.packBase-x.gross};});const ingredientsCost=rows.reduce((s,r)=>s+r.cost,0),n=order.count,costs={ingredients:ingredientsCost,labor:order.hours*order.rate*n,packaging:order.packaging*n,decoration:order.decoration*n,energy:order.energyKwh*order.energyPrice*n,overhead:order.overhead*n,delivery:order.delivery};const total=Object.values(costs).reduce((s,v)=>s+v,0),suggested=Math.ceil((total/(1-order.margin/100))/order.roundTo-1e-12)*order.roundTo,sale=order.sale??suggested,profit=sale-total,actualMargin=sale?profit/sale*100:null,portions=tiers.reduce((s,t)=>s+t.portionEstimate,0)*n;return {rows,shopping,tiers,costs,total,suggested,sale,profit,actualMargin,portions,perPortion:sale/portions,perCake:sale/n,volume:volume*n,allergens:[...allergens],shoppingCost:shopping.reduce((s,x)=>s+x.buyCost,0)};}
export function validateState(s){if(!s||s.version!==1)throw Error('Nieobsługiwana wersja kopii.');if(!Array.isArray(s.ingredients)||s.ingredients.length>1000||!Array.isArray(s.recipes)||s.recipes.length>300||!Array.isArray(s.quotes)||s.quotes.length>500)throw Error('Nieprawidłowa lub zbyt duża baza.');for(const list of [s.ingredients,s.recipes,s.quotes])if(new Set(list.map(x=>x.id)).size!==list.length)throw Error('Powtórzone identyfikatory.');validateSales(s.sales??[]);s.ingredients.forEach(validateIngredient);s.recipes.forEach(r=>validateRecipe(r,s.ingredients));validateOrder(s.order,s.recipes);for(const q of s.quotes){if(typeof q.id!=='string'||typeof q.name!=='string'||typeof q.date!=='string'||!q.snapshot)throw Error('Nieprawidłowa zapisana wycena.');if(q.snapshot.quotes?.length||q.snapshot.sales?.length)throw Error('Kopia wyceny nie może zawierać kolejnych wycen.');validateState({...q.snapshot,quotes:[],sales:[]});}return s;}

export const SALE_STATUSES={inquiry:'Zapytanie',confirmed:'Potwierdzone',production:'W przygotowaniu',ready:'Gotowe',delivered:'Wydane',cancelled:'Anulowane'};
export function saleBalance(s){const paid=Math.round((s.deposit+s.paid)*100)/100,balance=Math.round((s.price-paid)*100)/100;return {paid,balance,due:Math.max(0,balance),overpayment:Math.max(0,-balance)};}
export function validateSale(s){
  const text=(key,max,required=false)=>{if(typeof s[key]!=='string'||s[key].length>max||(required&&!s[key].trim()))throw Error('Zamówienie: nieprawidłowe pole '+key+'.');};
  if(!s||typeof s!=='object')throw Error('Nieprawidłowe zamówienie.');
  for(const k of ['id','number','title','customer'])text(k,160,true);
  for(const k of ['phone','email','occasion','flavor','inscription','colors'])text(k,300);
  for(const k of ['description','notes','allergies'])text(k,12000);
  text('address',1000);text('dueDate',10);text('dueTime',5);
  if(!Object.hasOwn(SALE_STATUSES,s.status)||!['pickup','delivery'].includes(s.fulfillment))throw Error('Nieprawidłowy status lub sposób odbioru.');
  if(!/^\d{4}-\d{2}-\d{2}$/.test(s.dueDate)||!Number.isFinite(Date.parse(s.dueDate+'T12:00:00Z'))||new Date(s.dueDate+'T12:00:00Z').toISOString().slice(0,10)!==s.dueDate)throw Error('Wpisz prawidłowy termin odbioru.');
  if(s.dueTime&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(s.dueTime))throw Error('Nieprawidłowa godzina.');
  for(const key of ['createdAt','updatedAt'])if(typeof s[key]!=='string'||!Number.isFinite(Date.parse(s[key])))throw Error('Nieprawidłowa data zapisu.');
  for(const key of ['price','deposit','paid']){finite(s[key],key);if(Math.abs(s[key]*100-Math.round(s[key]*100))>1e-5)throw Error('Kwoty podaj z dokładnością do groszy.');}
  finite(s.portions,'Liczba porcji',1,10000);if(!Number.isInteger(s.portions))throw Error('Podaj całkowitą liczbę porcji.');
  if(!Array.isArray(s.photos)||s.photos.length>8)throw Error('Zamówienie może mieć do 8 zdjęć.');
  const ids=new Set();for(const p of s.photos){if(!p||typeof p.id!=='string'||!p.id||ids.has(p.id)||typeof p.name!=='string'||p.name.length>200||typeof p.caption!=='string'||p.caption.length>500||typeof p.data!=='string'||p.data.length>450000||!/^data:image\/(?:jpeg|png|webp);base64,[A-Za-z0-9+/]+={0,2}$/.test(p.data))throw Error('Nieprawidłowe zdjęcie zamówienia.');ids.add(p.id);}
  if(s.quote!==null){if(!s.quote||typeof s.quote.name!=='string'||typeof s.quote.date!=='string'||!s.quote.snapshot)throw Error('Nieprawidłowe powiązanie wyceny.');const snap=s.quote.snapshot;if(snap.sales?.length||snap.quotes?.length)throw Error('Wycena zamówienia nie może zawierać archiwum ani zamówień.');validateState({...snap,sales:[],quotes:[]});}
  return s;
}
export function validateSales(sales){if(!Array.isArray(sales)||sales.length>1000)throw Error('Baza może zawierać do 1000 zamówień.');const ids=new Set(),numbers=new Set();let bytes=0;for(const s of sales){validateSale(s);if(ids.has(s.id)||numbers.has(s.number))throw Error('Powtórzony numer lub identyfikator zamówienia.');ids.add(s.id);numbers.add(s.number);bytes+=s.photos.reduce((n,p)=>n+p.data.length,0);}if(bytes>60*1024*1024)throw Error('Zdjęcia przekraczają limit 60 MB tej bazy. Zarchiwizuj kopię i usuń niepotrzebne zdjęcia.');return sales;}
