// Application smoke checks with DOM boundary stubs; these are not browser/E2E tests.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as engine from './engine.js';
import {initialState} from './data.js';
const source=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');
function app(){const els=new Map();const element=()=>({innerHTML:'',textContent:'',style:{},listeners:{},open:false,addEventListener(k,fn){this.listeners[k]=fn;},showModal(){this.open=true;},close(){this.open=false;}});const document={activeElement:null,querySelector(s){if(!els.has(s))els.set(s,element());return els.get(s);}};const store=new Map();const localStorage={getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)};const window={addEventListener(){},print(){}};const deps={...engine,initialState,document,localStorage,window,setTimeout:()=>0,clearTimeout:()=>{}};const api=Function(...Object.keys(deps),source+'\nreturn {render,handleAction,saveQuote,showRecipe,showIngredient,printDocument,getState:()=>state,setView:v=>{view=v;render();}};')(...Object.values(deps));return {...api,els,store,document};}
test('Every application view renders populated content without runtime errors',()=>{const a=app();for(const view of ['calculator','ingredients','recipes','pricing','quotes','help']){a.setView(view);const html=a.els.get('#app').innerHTML;assert.ok(html.length>1500);assert.ok(!html.includes('NaN'));assert.ok(!html.includes('undefined'));}});
test('New and existing ingredient and recipe editors render',()=>{const a=app();a.showIngredient();assert.ok(a.els.get('#editor').innerHTML.includes('Nowy składnik'));a.showRecipe('raspberry-cake');assert.ok(a.els.get('#editor').innerHTML.includes('Wanilia &amp; malina'));a.showRecipe('raspberry-cake',true);assert.ok(a.els.get('#editor').innerHTML.includes('kopia'));});
test('Saving a quote retains snapshot, persists, and renders archive',()=>{const a=app();a.saveQuote();assert.equal(a.getState().quotes.length,1);assert.ok(a.store.size);a.setView('quotes');assert.ok(a.els.get('#app').innerHTML.includes('Tort urodzinowy'));});
test('Both print documents and price list generate content',()=>{const a=app();for(const type of ['quote','production','pricing']){a.printDocument(type);assert.ok(a.els.get('#print-content').innerHTML.length>500);}a.printDocument('quote');assert.ok(!a.els.get('#print-content').innerHTML.includes('Pełny koszt'));});
test('User text is escaped in ordinary and printable views',()=>{const a=app();a.getState().order.name='<img src=x onerror=alert(1)>';a.render();a.printDocument('quote');assert.ok(!a.els.get('#app').innerHTML.includes('<img src=x'));assert.ok(a.els.get('#print-content').innerHTML.includes('&lt;img'));});
