// Smoke checks with DOM/storage boundary stubs, not real browser/E2E tests.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as engine from './engine.js';
import {initialState,migrateState} from './data.js';
const read=name=>fs.readFileSync(new URL(name,import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'');
const source=read('./sales-ui.js')+'\n'+read('./cooking.js')+'\n'+read('./app.js');
async function app({legacy=null,fail=false}={}){const els=new Map();const element=()=>({innerHTML:'',textContent:'',style:{},listeners:{},open:false,querySelector(){return null;},querySelectorAll(){return [];},addEventListener(k,fn){(this.listeners[k]??=[]).push(fn);},showModal(){this.open=true;},close(){this.open=false;}});const document={activeElement:null,querySelector(s){if(!els.has(s))els.set(s,element());return els.get(s);}};const store=new Map();if(legacy)store.set('pracownia-tortow:v1',JSON.stringify(legacy));const localStorage={getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)};let saved;class WorkshopStorage{constructor(){this.revision=0;this.lastRaw=null;}async load(){return saved??null;}async save(data){if(fail)throw Error('Quota exceeded');saved=structuredClone(data);this.lastRaw=saved;this.revision++;}}
const window={addEventListener(){},print(){},confirm(){return true;}};const deps={...engine,initialState,migrateState,WorkshopStorage,document,localStorage,window,setTimeout:()=>0,clearTimeout:()=>{}};const api=Function(...Object.keys(deps),source+'\nreturn {ready,render,handleAction,saveQuote,showRecipe,showIngredient,printDocument,salesUI,cookingUI,commitState,getState:()=>state,getError:()=>saveError,setView:v=>{view=v;render();}};')(...Object.values(deps));await api.ready;return {...api,els,store,document,saved:()=>saved};}
test('All seven views render without runtime errors',async()=>{const a=await app();for(const view of ['sales','calculator','ingredients','recipes','pricing','quotes','help']){a.setView(view);const html=a.els.get('#app').innerHTML;assert.ok(html.length>1500);assert.ok(!html.includes('NaN'));assert.ok(!html.includes('undefined'));}});
test('Ingredient and recipe editors render',async()=>{const a=await app();a.showIngredient();assert.ok(a.els.get('#editor').innerHTML.includes('Nowy składnik'));a.showRecipe('raspberry-cake');assert.ok(a.els.get('#editor').innerHTML.includes('Wanilia &amp; malina'));a.showRecipe('raspberry-cake',true);assert.ok(a.els.get('#editor').innerHTML.includes('kopia'));});
test('Quote snapshot excludes sales and photos, archive persists',async()=>{const a=await app();await a.saveQuote();assert.equal(a.getState().quotes.length,1);assert.deepEqual(a.getState().quotes[0].snapshot.sales,[]);assert.equal(a.saved().quotes.length,1);a.setView('quotes');assert.ok(a.els.get('#app').innerHTML.includes('Tort urodzinowy'));});
test('Both print documents and price list generate content',async()=>{const a=await app();for(const type of ['quote','production','pricing']){a.printDocument(type);assert.ok(a.els.get('#print-content').innerHTML.length>500);}a.printDocument('quote');assert.ok(!a.els.get('#print-content').innerHTML.includes('Pełny koszt'));});
test('User text is escaped in ordinary and printable views',async()=>{const a=await app();a.getState().order.name='<img src=x onerror=alert(1)>';a.render();a.printDocument('quote');assert.ok(!a.els.get('#app').innerHTML.includes('<img src=x'));assert.ok(a.els.get('#print-content').innerHTML.includes('&lt;img'));});
test('Legacy data migrate without losing recipes or quotes',async()=>{const legacy=initialState();delete legacy.sales;legacy.order.name='Moja stara kalkulacja';const a=await app({legacy});assert.equal(a.getState().order.name,'Moja stara kalkulacja');assert.deepEqual(a.getState().sales,[]);assert.equal(a.saved().recipes.length,legacy.recipes.length);});
test('Sales editor contains descriptions, photos, payments and quotation control',async()=>{const a=await app();a.salesUI.open();const html=a.els.get('#sales-editor').innerHTML;for(const text of ['description','sales-photos','deposit','paid','sales-quote-choice','inscription','customer'])assert.ok(html.includes(text));});
test('Sales order from calculator has independent quotation, detail and list render safely',async()=>{const a=await app();const sale=a.salesUI.fresh();sale.title='<script>bad</script>';sale.customer='Anna';sale.price=350;sale.deposit=100;sale.status='confirmed';const next=structuredClone(a.getState());next.sales.push(sale);await a.commitState(next);a.setView('sales');const html=a.els.get('#app').innerHTML;assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>bad'));a.salesUI.detail(sale);assert.ok(a.els.get('#sales-editor').innerHTML.includes('250'));a.salesUI.open(null,true);assert.ok(a.els.get('#sales-editor').innerHTML.includes('Tort urodzinowy'));});
test('Storage failure blocks overwrite and surfaces recovery information',async()=>{const a=await app({fail:true});assert.ok(a.getError().includes('Nie udało się wczytać'));await assert.rejects(()=>a.commitState(initialState()),/Zapis wstrzymany/);assert.equal(a.saved(),undefined);});

test('Cooking dialog shows scaled ingredients and recipe editor exposes steps',async()=>{const a=await app();await a.cookingUI.open(a.getState());const html=a.els.get('#cooking-dialog').innerHTML;assert.ok(html.includes('Zrób krok po kroku'));assert.ok(html.includes('9 szt'));assert.ok(html.includes('Odhacz wykonany'));a.showRecipe('raspberry-cake');const editor=a.els.get('#editor').innerHTML;assert.ok(editor.includes('recipe-step'));assert.ok(editor.includes('Przygotowanie krok po kroku'));});
